# Generated by Django 5.1.7 on 2025-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
    ]
