# Generated by Django 5.1.7 on 2025-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_reminder_created_at_reminder_repeat_yearly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
