# Generated by Django 5.2 on 2025-04-24 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_chapter_subname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="whatsapp_number",
        ),
        migrations.AddField(
            model_name="reminder",
            name="email",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pdf",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
